use_frameworks!

platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'iosApp' do
    pod 'Kingfisher', '~> 4.0'
    pod 'MaterialComponents'
    pod 'Firebase/Core'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'lib', :path => '../sessionize/lib'


    # Script to fix 'too many symbol files 
    # warning on App Store Connect:
    
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
      end
    end

end
